AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: ARRAT Step Function Stack

Parameters:
  InstanceId: 
    Type: String 
    Description: ARRAT GPU instance
    Default: i-0c8e82483c8d41a38 
    
Resources: 

  ARRATCodeBucket:
    Type: AWS::S3::Bucket

  ARRATSessionInputBucket:
    Type: AWS::S3::Bucket

  ARRATSessionOutputBucket:
    Type: AWS::S3::Bucket

  ARRATStateMachine: 
    Type: AWS::Serverless::StateMachine 
    Properties: 
      DefinitionUri: ../statemachine/arrat.asl.json 
      DefinitionSubstitutions:
        ArratInstanceId: !Ref InstanceId
        ArratCodeBucket: !Ref ARRATCodeBucket
        ARRATSessionInputBucket: !Ref ARRATSessionInputBucket
        ARRATSessionOutputBucket: !Ref ARRATSessionOutputBucket
      Role: !GetAtt SSMStepFunctionRole.Arn

  SSMStepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: stepfunctionsxraypolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - 'xray:PutTraceSegments'
              - 'xray:PutTelemetryRecords'
              - 'xray:GetSamplingRules'
              - 'xray:GetSamplingTargets'
              Resource:
              - '*'
            - Effect: Allow
              Action:
              - 'ssm:StartAutomationExecution'
              Resource:
              - '*'
            - Effect: Allow
              Action:
              - 's3:GetObject'
              Resource:
              - !Sub "arn:aws:s3:::${ARRATCodeBucket}/*"
            - Effect: Allow
              Action:
              - 's3:GetObject'
              Resource:
              - !Sub "arn:aws:s3:::${ARRATSessionInputBucket}/*"
            - Effect: Allow
              Action:
              - 's3:PutObject'
              Resource:
              - !Sub "arn:aws:s3:::${ARRATSessionOutputBucket}/*"

      RoleName: SSMStepFunctionRole      

  FrontendBucketOACPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ARRATSessionOutputBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub ${ARRATSessionOutputBucket.Arn}/*
            Principal:
              Service: cloudfront.amazonaws.com
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: CloudFrontOAC
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
        Description: OAC for S3 bucket

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          TargetOriginId: !GetAtt ARRATSessionOutputBucket.Arn
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized PolicyId
        Enabled: true
        Origins:
          - DomainName: !GetAtt ARRATSessionOutputBucket.RegionalDomainName
            Id: !GetAtt ARRATSessionOutputBucket.Arn
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
            S3OriginConfig:
              OriginAccessIdentity: ""
        PriceClass: PriceClass_100
        HttpVersion: http2

Outputs: 

  ARRATStateMachineArn: 
    Description: ARN of the ARRAT Step Function state machine
    Value: !Ref ARRATStateMachine

  SessionInputBucketName:
    Description: Name of the S3 bucket for ARRAT session input data
    Value: !Ref ARRATSessionInputBucket

  SessionOutputBucketName:
    Description: Name of the S3 bucket for ARRAT session output data
    Value: !Ref ARRATSessionOutputBucket

  ARRATStateMachineName:
    Description: Name of the ARRAT Step Function state machine
    Value: !GetAtt ARRATStateMachine.Name

  CloudFrontDomain:
    Description: Output CloudFront Distribution
    Value: !GetAtt CloudFrontDistribution.DomainName
