AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: ARRAT Step Function Stack

Parameters:
  InstanceId: 
    Type: String 
    Description: ARRAT GPU instance
    Default: i-0c8e82483c8d41a38 
    
Resources: 

  ARRATCodeBucket:
    Type: AWS::S3::Bucket

  ARRATSessionInputBucket:
    Type: AWS::S3::Bucket

  ARRATSessionOutputBucket:
    Type: AWS::S3::Bucket

  ARRATStateMachine: 
    Type: AWS::Serverless::StateMachine 
    Properties: 
      DefinitionUri: ../statemachine/arrat.asl.json 
      DefinitionSubstitutions:
        ArratInstanceId: !Ref InstanceId
        ArratCodeBucket: !Ref ARRATCodeBucket
        ARRATSessionInputBucket: !Ref ARRATSessionInputBucket
        ARRATSessionOutputBucket: !Ref ARRATSessionOutputBucket
      Role: !GetAtt SSMStepFunctionRole.Arn

  SSMStepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: stepfunctionsxraypolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - 'xray:PutTraceSegments'
              - 'xray:PutTelemetryRecords'
              - 'xray:GetSamplingRules'
              - 'xray:GetSamplingTargets'
              Resource:
              - '*'
            - Effect: Allow
              Action:
              - 'ssm:StartAutomationExecution'
              Resource:
              - '*'
            - Effect: Allow
              Action:
              - 's3:GetObject'
              Resource:
              - !Sub "arn:aws:s3:::${ARRATCodeBucket}/*"
            - Effect: Allow
              Action:
              - 's3:GetObject'
              Resource:
              - !Sub "arn:aws:s3:::${ARRATSessionInputBucket}/*"
            - Effect: Allow
              Action:
              - 's3:PutObject'
              Resource:
              - !Sub "arn:aws:s3:::${ARRATSessionOutputBucket}/*"

      RoleName: SSMStepFunctionRole      

Outputs: 

  ARRATStateMachineArn: 
    Description: ARRAT state machine 
    Value: !Ref ARRATStateMachine
