AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ARRAT EC2 Ingestion stack 

Parameters:
  AmiId:
    Type: String 
    Description: ami id 
    Default: ami-08a3b3d19e53d61e3
  SecurityGroupId: 
    Type: String
    Description: security group id 
  VPCId:
    Type: String
    Description: vpc id
  VPCSubnetId: 
    Type: String 
    Description: vpc subnet id 
  KeyPairName:
    Type: String 
    Description: ec2 key pair 

Resources:

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Path: /
      RoleName: InstanceRole

  ARRATInstance:
    Type: AWS::EC2::Instance
    Properties: 
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Ref AmiId
      KeyName: !Ref KeyPairName
      InstanceType: g4dn.xlarge
      SecurityGroupIds:
        - !Ref SecurityGroupId
      SubnetId: !Ref VPCSubnetId
      BlockDeviceMappings:
      -
        DeviceName: "/dev/sda1"
        Ebs:
          VolumeSize: 600
          VolumeType: gp3
      Tags:
      - Key: Name
        Value: GPU ARRAT

  InstanceProfile: 
    Type: AWS::IAM::InstanceProfile 
    Properties: 
      Path: "/"
      Roles: 
        - !Ref InstanceRole


