AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ARRAT EC2 Ingestion stack 

Parameters:
  AmiId:
    Type: String 
    Description: ami id 
    Default: ami-0481a2c9118bf0a59
  SecurityGroupId: 
    Type: String
    Description: security group id 
    Default: sg-0468f4113a4e36d34 
  VPCId:
    Type: String
    Description: vpc id
    Default: vpc-00465e9c97c4937fd
  VPCSubnetId: 
    Type: String 
    Description: vpc subnet id 
    Default: subnet-07498d8504facc19a
  KeyPairName:
    Type: String 
    Description: ec2 key pair 
    Default: i70_tac_keypair

Resources:

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Path: /
      RoleName: InstanceRole

  ARRATInstance:
    Type: AWS::EC2::Instance
    Properties: 
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Ref AmiId
      KeyName: !Ref KeyPairName
      InstanceType: g4dn.xlarge
      SecurityGroupIds:
        - !Ref SecurityGroupId
      SubnetId: !Ref VPCSubnetId
      BlockDeviceMappings:
      -
        DeviceName: "/dev/sda"
        Ebs:
          VolumeSize: 600
          VolumeType: gp3
      Tags:
      - Key: Name
        Value: GPU ARRAT

  InstanceProfile: 
    Type: AWS::IAM::InstanceProfile 
    Properties: 
      Path: "/"
      Roles: 
        - !Ref InstanceRole

  # InstallSSMAgentAssociation:
  #   Type: AWS::SSM::Association
  #   Properties:
  #     Name: AWS-ConfigureAWSPackage
  #     Targets:
  #       - Key: tag:Environment
  #         Values:
  #           - Production
  #     Parameters:
  #       action:
  #         - Install
  #       source:
  #         - https://s3.amazonaws.com/amazon-ssm-us-east-1/ssm-agent/
  #       packageName:
  #         - AmazonSSMAgent
  #     ScheduleExpression: cron(0 0 ? * * *) # Run daily

